### ISSUE TITLE
even_odd_site.py logic error in line 7

### ISSUE THREAD

**Issue by mbeckage** [mbeckage/inClassActivity_3-21#10]
Description: varible i is used as a varible to loop through up to 50, but 'i' is not initialized.
Steps to reproduce: use a variable but don't initalize it
Expected behavior: program won't run 
Actual behavior: n/a because I didn't run the code.
Screenshots: n/a
Additional Information: n/a
Possible Solution: add 'int i = 1' above the loop
Related Issues: n/a
Priority: low (easy fix)
Reproducibility: never if the user is careful
Impact: low

**Comment by jsdrisco** [comment]
Fixed; implemented suggested solution - added 
`i = 0`
above loop.

**Comment by jsdrisco** [comment]
Fixed; implemented suggested solution - added
i = 0
above loop.
