### ISSUE TITLE
rgb_to_hex.py

### ISSUE THREAD

**Issue by hak2711** [mbeckage/inClassActivity_3-21#14]
Description: Wrong result

Steps to Reproduce: run the code

Expected Behavior: test with hex_color = rgb_to_hex(255, 127, 0) # returns "FF7F00"

Actual Behavior: test with hex_color = rgb_to_hex(255, 127, 0) # returns "007F00"

Possible Solution: change into 'g = max(0, max(255, b))' in line 3

Priority: High

Reproducibility: Always

Impact: high

**Comment by cjrinaldi** [comment]
fixed by changing min to max in line 3
