### ISSUE TITLE
sum_even_fibonacci.cc

### ISSUE THREAD

**Issue by hak2711** [mbeckage/inClassActivity_3-21#8]
Description: Use of undeclared identifier 'std'

Steps to Reproduce: run the code

Expected Behavior: sum all the even fibonacci numbers that are below 4,000,000

Actual Behavior: has an error

Screenshots
![image](https://user-images.githubusercontent.com/67725652/226741754-f70b09a7-60bb-4650-9266-3f7f023207e4.png)

Possible Solution: #include <iostream>

Priority: high priority

Reproducibility: Always

Impact: high

**Comment by cjrinaldi** [comment]
Fixed by adding #include <iostream> to first line
