### ISSUE TITLE
even_odd_site.py compilier issue in line 15

### ISSUE THREAD

**Issue by mbeckage** [mbeckage/inClassActivity_3-21#9]
Description: varible name is mistyped as 'fin' but needs to be 'f' as 'fin' does not exist 
Steps to reproduce: retype 'f' as 'fin' by accident.
Expected behavior: program won't run as 'fin' is an undeclared variable.
Actual behavior: n/a because I didn't run the code.
Screenshots: n/a
Additional Information: n/a
Possible Solution: replace 'fin' with 'f'
Related Issues: n/a
Priority: low (easy fix)
Reproducibility: never if the user is careful
Impact: low

**Comment by jsdrisco** [comment]
Fixed issue; implemented suggested solution of changing fin back to f.
